spring:
  application:
    name: customer-service
  profiles:
    active: dev
  main:
    banner-mode: off

logging:
  level:
    root: INFO
    com.web.pharma.inventory: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/   # Eureka server URL