server:
  port: 8081

spring:
  application:
    name: pharmacy-gateway

  main:
    banner-mode: off

jwt:
  secret: AvHGRK8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadweheufHNyG
  #secret: ${SECURITY_JWT_SECRET:default_one}

logging:
  level:
    org.springframework: info