spring:
  datasource:
    url: jdbc:h2:mem:medstore;DB_CLOSE_DELAY=-1;MODE=Oracle
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
flyway:
  enabled: false
server:
  port: 8081
