spring:
  datasource:
    url: jdbc:oracle:thin:@//prod-db-host:1521/PRODDB
    username: medstore_prod
    password: replace_with_secret
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
flyway:
  enabled: true
  locations: classpath:db/migration
