CREATE TABLE medicine (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id VARCHAR2(50) UNIQUE NOT NULL,
  item_type VARCHAR2(50) NOT NULL,
  name VARCHAR2(255) NOT NULL,
  strength_mg NUMBER,
  company VARCHAR2(255),
  expiry_date DATE,
  quantity NUMBER,
  unit_price NUMBER(12,2),
  total_value NUMBER(18,2)
);

CREATE TABLE inventory_batch (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  medicine_id NUMBER NOT NULL,
  batch_no VARCHAR2(64) NOT NULL,
  expiry_date DATE NOT NULL,
  mrp NUMBER(12,2),
  purchase_price NUMBER(12,2),
  sell_price NUMBER(12,2),
  pack_size NUMBER,
  total_units NUMBER,
  available_units NUMBER,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_batch_med FOREIGN KEY (medicine_id) REFERENCES medicine(id)
);

CREATE TABLE supplier (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(255) NOT NULL,
  phone VARCHAR2(32),
  gstin VARCHAR2(32),
  address VARCHAR2(500)
);

CREATE TABLE purchase (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_id NUMBER NOT NULL,
  invoice_date DATE,
  invoice_no VARCHAR2(64),
  total_amount NUMBER(14,2),
  CONSTRAINT fk_purchase_supplier FOREIGN KEY (supplier_id) REFERENCES supplier(id)
);

CREATE TABLE purchase_item (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_id NUMBER NOT NULL,
  medicine_id NUMBER NOT NULL,
  batch_no VARCHAR2(64),
  expiry_date DATE,
  quantity_units NUMBER,
  pack_size_units NUMBER,
  mrp NUMBER(12,2),
  purchase_price NUMBER(12,2),
  sell_price NUMBER(12,2),
  CONSTRAINT fk_pi_purchase FOREIGN KEY (purchase_id) REFERENCES purchase(id),
  CONSTRAINT fk_pi_med FOREIGN KEY (medicine_id) REFERENCES medicine(id)
);

CREATE TABLE sale (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  total_amount NUMBER(14,2)
);

CREATE TABLE sale_item (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id NUMBER NOT NULL,
  medicine_id NUMBER NOT NULL,
  batch_id NUMBER NOT NULL,
  quantity_units NUMBER,
  unit_price NUMBER(12,2),
  CONSTRAINT fk_si_sale FOREIGN KEY (sale_id) REFERENCES sale(id),
  CONSTRAINT fk_si_med FOREIGN KEY (medicine_id) REFERENCES medicine(id),
  CONSTRAINT fk_si_batch FOREIGN KEY (batch_id) REFERENCES inventory_batch(id)
);

CREATE TABLE inventory_txn (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  medicine_id NUMBER NOT NULL,
  batch_id NUMBER,
  delta_units NUMBER,
  occurred_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  reason VARCHAR2(32),
  reference VARCHAR2(64)
);
-- seed sample medicine
INSERT INTO medicine (item_id, item_type, name, strength_mg, company, expiry_date, quantity, unit_price, total_value)
VALUES ('MS0001', 'Ointment', 'Paracetamol', NULL, 'Amulya', DATE '2026-08-19', 254, 460.23, 116898.42);
